### ISSUE TITLE
第一次搭建博客 - Mrkaixin

### ISSUE THREAD

**Issue by FirstKaiXin** [FirstKaiXin/FirstKaiXin.github.io#4]
https://firstkaixin.github.io/2019/03/17/%E6%90%AD%E5%8D%9A%E5%AE%A2/ 

 0x00因为感觉最近特别的浮躁所以想歇一歇，正好因为各种情况也想搭建博客，在网上找了很多的搭建博客的方法，最后还是选用了hexo+github这个，应为作为一个程序猿还是想多跟GitHub打交道。废话不多说。这里主要是讲一些搭建博客时候所遇到的一些问题

**Comment by cheemanl** [comment]
大佬牛逼！！！！！

**Comment by FirstKaiXin** [comment]
> @cheemanl
> 大佬牛逼！！！！！

**喊大哥**

**Comment by cheemanl** [comment]
> @FirstKaiXin
> > @cheemanl
> > 大佬牛逼！！！！！
> 
> **喊大哥**
> 

你做梦

**Comment by cheemanl** [comment]
> @FirstKaiXin
> > @cheemanl
> > 大佬牛逼！！！！！
> 
> **喊大哥**
> 

臭弟弟
